/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-22 09:02:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Joinfrm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("#header {\r\n");
      out.write("\tbackground-color: #58557A;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav {\r\n");
      out.write("\tbackground-color: #9D9BCC;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tborder: 1px solid #373D40;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-left: 38%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr td {\r\n");
      out.write("\tborder: 1px solid #373D40;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\t/* \tborder-left: none; */\r\n");
      out.write("\t/* \tborder-right: none; */\r\n");
      out.write("\t/* \tborder-top: none; */\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#div_join {\r\n");
      out.write("\tbackground-color: #DDDDF0;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #778268;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<div id=\"nav\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"div_join\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\"><b style=\"font-size: 30px;\">홈쇼핑 회원 등록</b></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<form action=\"#\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>회원번호(자동발생)</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"custno\" maxlength=\"20\" id=\"custno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${custno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>회원성명</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"custname\" maxlength=\"20\" id=\"custname\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>회원전화</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"phone\" maxlength=\"20\" id=\"phone\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>회원주소</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"address\" maxlength=\"20\" id=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>가입일자</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"joindate\" maxlength=\"20\" id=\"joindate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>고객등급(A:vip,B:일반,C:직원)</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"grade\" maxlength=\"20\" id=\"grade\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>도시코드</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"city\" maxlength=\"20\" id=\"city\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"btn\" value=\"회원가입\" formaction=\"memberjoin\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"select\" value=\"조회\" style=\"margin-left: 30px;\" formaction=\"memberlist\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\"#btn\").click(function() {\r\n");
      out.write("\t\t   if ($(\"#custno\").val() == \"\") {\r\n");
      out.write("\t\t      alert(\"회원번호.\");\r\n");
      out.write("\t\t      $(\"#custno\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#custname\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"회원성명이 입력되지않았습니다\");\r\n");
      out.write("\t\t      $(\"#custname\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#phone\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("\t\t      $(\"#phone\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#address\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"주소를 입력해주세요.\");\r\n");
      out.write("\t\t      $(\"#address\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#joindate\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"가입일을 입력해주세요.\");\r\n");
      out.write("\t\t      $(\"#joindate\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#grade\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"등급을 입력해주세요.\");\r\n");
      out.write("\t\t      $(\"#grade\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else if($(\"#city\").val() == \"\"){\r\n");
      out.write("\t\t      alert(\"도시코드를 입력해주세요.\");\r\n");
      out.write("\t\t      $(\"#city\").focus();\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"button\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   else{\r\n");
      out.write("\t\t      alert(\"회원등록이 완료되었습니다.\");\r\n");
      out.write("\t\t      $(\"#btn\").prop(\"type\", \"submit\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
